# Generated by Django 5.0.6 on 2026-05-21 13:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostEstimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layout_id', models.UUIDField(db_index=True)),
                ('country', models.CharField(choices=[('NG', 'Nigeria'), ('KE', 'Kenya'), ('GH', 'Ghana'), ('ET', 'Ethiopia'), ('ZA', 'South Africa'), ('SN', 'Senegal')], max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=5)),
                ('breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_estimates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabourRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_type', models.CharField(choices=[('mason', 'Mason'), ('carpenter', 'Carpenter'), ('plumber', 'Plumber'), ('electrician', 'Electrician'), ('labourer', 'General Labourer')], max_length=50)),
                ('country', models.CharField(choices=[('NG', 'Nigeria'), ('KE', 'Kenya'), ('GH', 'Ghana'), ('ET', 'Ethiopia'), ('ZA', 'South Africa'), ('SN', 'Senegal')], max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('rate_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['country', 'skill_type'],
                'indexes': [models.Index(fields=['country', 'skill_type'], name='cost_estima_country_4ed4f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('wall', 'Wall'), ('foundation', 'Foundation'), ('roof', 'Roof'), ('floor', 'Floor'), ('window', 'Window'), ('insulation', 'Insulation'), ('finishing', 'Finishing')], max_length=50)),
                ('unit', models.CharField(max_length=30)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=5)),
                ('country', models.CharField(choices=[('NG', 'Nigeria'), ('KE', 'Kenya'), ('GH', 'Ghana'), ('ET', 'Ethiopia'), ('ZA', 'South Africa'), ('SN', 'Senegal')], max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('carbon_score', models.FloatField(default=0.0)),
                ('is_eco', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['country', 'category', 'name'],
                'indexes': [models.Index(fields=['country', 'category'], name='cost_estima_country_500707_idx'), models.Index(fields=['country', 'city', 'category'], name='cost_estima_country_f6c4ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='TCOProjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layout_id', models.UUIDField(db_index=True)),
                ('upfront_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=5)),
                ('projection_years', models.IntegerField(default=5)),
                ('annual_savings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_savings', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payback_months', models.IntegerField()),
                ('savings_breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tco_projections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
