"""
Management command: python manage.py seed_plants

Populates the Plant catalogue with native African flora across all climate
zones, sun levels, soils, and water-conservation profiles.

Data sourced from the data team's regional flora datasets (Central, East,
North Africa) — 168 unique species deduplicated by scientific name and
mapped onto the API's enum vocabulary.

Re-running this command is idempotent (uses get_or_create on
scientific_name). Pass --reset to wipe and reseed.
"""
from django.core.management.base import BaseCommand
from apps.plants.models import Plant


SAMPLE_PLANTS = [{'name': 'Acacia (Acacia senegal)',
  'scientific_name': 'Acacia senegal',
  'climate_zones': ['arid_semi_arid', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'ultra_low',
  'water_frequency': 'Drought-tolerant once established',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Drought-tolerant native',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Acacia'},
 {'name': 'Acacia (Vachellia tortilis)',
  'scientific_name': 'Vachellia tortilis',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'ultra_low',
  'water_frequency': 'Drought-tolerant once established',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Drought-tolerant native',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Acacia'},
 {'name': 'Acacia ehrenbergiana',
  'scientific_name': 'Acacia ehrenbergiana',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'ultra_low',
  'water_frequency': 'Drought-tolerant once established',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Drought-tolerant native',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Acacia+ehrenbergiana'},
 {'name': 'Acacia nilotica',
  'scientific_name': 'Acacia nilotica',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Acacia+nilotica'},
 {'name': 'African Bamboo',
  'scientific_name': 'Diospyros crassiflora',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=African+Bamboo'},
 {'name': 'African Blue Lily',
  'scientific_name': 'Milicia excelsa',
  'climate_zones': ['tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy', 'sandy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Rainforest species',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=African+Blue+Lily'},
 {'name': 'African Breadfruit (Elaeis guineensis)',
  'scientific_name': 'Elaeis guineensis',
  'climate_zones': ['tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['clay', 'loamy'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=African+Breadfruit'},
 {'name': 'African Breadfruit (Khaya ivorensis)',
  'scientific_name': 'Khaya ivorensis',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy', 'sandy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=African+Breadfruit'},
 {'name': 'African Cherry',
  'scientific_name': 'Vigna unguiculata',
  'climate_zones': ['arid_semi_arid', 'tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy', 'sandy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=African+Cherry'},
 {'name': 'African False Nutmeg',
  'scientific_name': 'Arachis hypogaea',
  'climate_zones': ['arid_semi_arid', 'tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy', 'sandy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=African+False+Nutmeg'},
 {'name': 'African Fan Palm',
  'scientific_name': 'Pennisetum purpureum',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=African+Fan+Palm'},
 {'name': 'African Fern Pine (Cenchrus americanus)',
  'scientific_name': 'Cenchrus americanus',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=African+Fern+Pine'},
 {'name': 'African Fern Pine (Irvingia gabonensis)',
  'scientific_name': 'Irvingia gabonensis',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['partial'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['native'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=African+Fern+Pine'},
 {'name': 'African Gardenia',
  'scientific_name': 'Aucoumea klaineana',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy', 'sandy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=African+Gardenia'},
 {'name': 'African Mahogany',
  'scientific_name': 'Raphia hookeri',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['peat'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=African+Mahogany'},
 {'name': 'African Padauk',
  'scientific_name': 'Baillonella toxisperma',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=African+Padauk'},
 {'name': 'African Peach',
  'scientific_name': 'Millettia laurentii',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['partial'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['native'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=African+Peach'},
 {'name': 'African Pear (Safou)',
  'scientific_name': 'Dacryodes edulis',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=African+Pear+%28Safou%29'},
 {'name': 'African Pearl Orchid',
  'scientific_name': 'Gnetum africanum',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['partial'],
  'soil_types': ['peat'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['native'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=African+Pearl+Orchid'},
 {'name': 'African Tulip Tree',
  'scientific_name': 'Cola acuminata',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['partial'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['native'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=African+Tulip+Tree'},
 {'name': 'African Violet',
  'scientific_name': 'Saintpaulia ionantha',
  'climate_zones': ['tropical_highland'],
  'sun_exposure': ['partial'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['native'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/4a7c4e/ffffff.png?text=African+Violet'},
 {'name': 'African Walnut',
  'scientific_name': 'Entandrophragma cylindricum',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['clay', 'loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=African+Walnut'},
 {'name': 'Agave',
  'scientific_name': 'Agave americana',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'ultra_low',
  'water_frequency': 'Drought-tolerant once established',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Drought-tolerant native',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Agave'},
 {'name': 'Aleppo Pine',
  'scientific_name': 'Pinus halepensis',
  'climate_zones': ['mediterranean'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Mediterranean native',
  'image_url': 'https://placehold.co/640x480/7a8a5c/ffffff.png?text=Aleppo+Pine'},
 {'name': 'Almond',
  'scientific_name': 'Prunus dulcis',
  'climate_zones': ['mediterranean'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Mediterranean native',
  'image_url': 'https://placehold.co/640x480/7a8a5c/ffffff.png?text=Almond'},
 {'name': 'Aloe Vera',
  'scientific_name': 'Aloe vera',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Aloe+Vera'},
 {'name': 'Aloe vera',
  'scientific_name': 'Aloe barbadensis miller',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'ultra_low',
  'water_frequency': 'Drought-tolerant once established',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Drought-tolerant native',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Aloe+vera'},
 {'name': 'Apricot',
  'scientific_name': 'Prunus armeniaca',
  'climate_zones': ['mediterranean'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Mediterranean native',
  'image_url': 'https://placehold.co/640x480/7a8a5c/ffffff.png?text=Apricot'},
 {'name': 'Argan Tree',
  'scientific_name': 'Argania spinosa',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Argan+Tree'},
 {'name': 'Atlas Cedar',
  'scientific_name': 'Cedrus atlantica',
  'climate_zones': ['tropical_highland'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/4a7c4e/ffffff.png?text=Atlas+Cedar'},
 {'name': 'Avocado',
  'scientific_name': 'Persea americana',
  'climate_zones': ['arid_semi_arid', 'tropical_highland', 'tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy', 'sandy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Avocado'},
 {'name': 'Bambara Groundnut',
  'scientific_name': 'Prunus africana',
  'climate_zones': ['tropical_highland'],
  'sun_exposure': ['partial'],
  'soil_types': ['loamy', 'peat'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['native'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/4a7c4e/ffffff.png?text=Bambara+Groundnut'},
 {'name': 'Banana (Musa acuminata)',
  'scientific_name': 'Musa acuminata',
  'climate_zones': ['tropical_rainforest'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Rainforest species',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=Banana'},
 {'name': 'Banana (Musa spp)',
  'scientific_name': 'Musa spp',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Banana'},
 {'name': 'Banana (Musa spp.)',
  'scientific_name': 'Musa spp.',
  'climate_zones': ['tropical_highland', 'tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/4a7c4e/ffffff.png?text=Banana'},
 {'name': 'Baobab',
  'scientific_name': 'Adansonia digitata',
  'climate_zones': ['arid_semi_arid', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['lateritic_red_clay', 'sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Baobab'},
 {'name': 'Barley',
  'scientific_name': 'Hordeum vulgare',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Barley'},
 {'name': 'Basil',
  'scientific_name': 'Ocimum basilicum',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Basil'},
 {'name': 'Beach Grass',
  'scientific_name': 'Ammophila arenaria',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Beach+Grass'},
 {'name': 'Bitter Kola',
  'scientific_name': 'Lophira alata',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Bitter+Kola'},
 {'name': 'Bitter leaf',
  'scientific_name': 'Vernonia amygdalina',
  'climate_zones': ['tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun', 'partial'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['humid-loving'],
  'care_tips': [],
  'impact_label': 'Rainforest species',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=Bitter+leaf'},
 {'name': 'Bougainvillea',
  'scientific_name': 'Bougainvillea spectabilis',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Bougainvillea'},
 {'name': 'Bubinga',
  'scientific_name': 'Ricinodendron heudelotii',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Bubinga'},
 {'name': 'Cabbage',
  'scientific_name': 'Brassica oleracea',
  'climate_zones': ['tropical_highland', 'tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Rainforest species',
  'image_url': 'https://placehold.co/640x480/4a7c4e/ffffff.png?text=Cabbage'},
 {'name': 'Capers',
  'scientific_name': 'Capparis spinosa',
  'climate_zones': ['mediterranean'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Mediterranean native',
  'image_url': 'https://placehold.co/640x480/7a8a5c/ffffff.png?text=Capers'},
 {'name': 'Carob Tree',
  'scientific_name': 'Ceratonia siliqua',
  'climate_zones': ['mediterranean'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Mediterranean native',
  'image_url': 'https://placehold.co/640x480/7a8a5c/ffffff.png?text=Carob+Tree'},
 {'name': 'Cashew',
  'scientific_name': 'Anacardium occidentale',
  'climate_zones': ['arid_semi_arid', 'tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['lateritic_red_clay', 'sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Cashew'},
 {'name': 'Cassava',
  'scientific_name': 'Manihot esculenta',
  'climate_zones': ['tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy', 'sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Rainforest species',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=Cassava'},
 {'name': 'Castor Plant',
  'scientific_name': 'Ricinus communis',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Castor+Plant'},
 {'name': 'Chickpea',
  'scientific_name': 'Cicer arietinum',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Chickpea'},
 {'name': 'Cocoa',
  'scientific_name': 'Theobroma cacao',
  'climate_zones': ['tropical_rainforest'],
  'sun_exposure': ['partial'],
  'soil_types': ['loamy'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['humid-loving'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=Cocoa'},
 {'name': 'Coconut',
  'scientific_name': 'Cocos nucifera',
  'climate_zones': ['arid_semi_arid', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy', 'sandy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Coconut'},
 {'name': 'Coffee (Coffea arabica)',
  'scientific_name': 'Coffea arabica',
  'climate_zones': ['tropical_highland'],
  'sun_exposure': ['partial'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['native'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/4a7c4e/ffffff.png?text=Coffee'},
 {'name': 'Coffee (Coffea robusta)',
  'scientific_name': 'Coffea robusta',
  'climate_zones': ['tropical_highland'],
  'sun_exposure': ['partial'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['native'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/4a7c4e/ffffff.png?text=Coffee'},
 {'name': 'Coriander',
  'scientific_name': 'Coriandrum sativum',
  'climate_zones': ['mediterranean'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Mediterranean native',
  'image_url': 'https://placehold.co/640x480/7a8a5c/ffffff.png?text=Coriander'},
 {'name': 'Cotton',
  'scientific_name': 'Gossypium hirsutum',
  'climate_zones': ['arid_semi_arid', 'tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy', 'sandy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Cotton'},
 {'name': 'Croton plant',
  'scientific_name': 'Codiaeum variegatum',
  'climate_zones': ['tropical_rainforest'],
  'sun_exposure': ['full_sun', 'partial'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['humid-loving'],
  'care_tips': [],
  'impact_label': 'Rainforest species',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=Croton+plant'},
 {'name': 'Date Palm',
  'scientific_name': 'Phoenix dactylifera',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'ultra_low',
  'water_frequency': 'Drought-tolerant once established',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Drought-tolerant native',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Date+Palm'},
 {'name': 'Date Palm (Wild)',
  'scientific_name': 'Phoenix reclinata',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Date+Palm+%28Wild%29'},
 {'name': 'Date Palm Seedling',
  'scientific_name': 'Phoenix dactylifera (young)',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Date+Palm+Seedling'},
 {'name': 'Date Shrub',
  'scientific_name': 'Ziziphus spina-christi',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'ultra_low',
  'water_frequency': 'Drought-tolerant once established',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Drought-tolerant native',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Date+Shrub'},
 {'name': 'Desert Date',
  'scientific_name': 'Balanites aegyptiaca',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'ultra_low',
  'water_frequency': 'Drought-tolerant once established',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Drought-tolerant native',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Desert+Date'},
 {'name': 'Eru (Okok) (Coffea liberica)',
  'scientific_name': 'Coffea liberica',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['partial'],
  'soil_types': ['peat'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['native'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Eru+%28Okok%29'},
 {'name': 'Eru (Okok) (Terminalia superba)',
  'scientific_name': 'Terminalia superba',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['peat'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Eru+%28Okok%29'},
 {'name': 'Eru (Okok) (Yushania alpina)',
  'scientific_name': 'Yushania alpina',
  'climate_zones': ['tropical_highland'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['peat'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/4a7c4e/ffffff.png?text=Eru+%28Okok%29'},
 {'name': 'Eucalyptus (Eucalyptus camaldulensis)',
  'scientific_name': 'Eucalyptus camaldulensis',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Eucalyptus'},
 {'name': 'Eucalyptus (Eucalyptus spp.)',
  'scientific_name': 'Eucalyptus spp.',
  'climate_zones': ['tropical_highland'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/4a7c4e/ffffff.png?text=Eucalyptus'},
 {'name': 'Euphorbia',
  'scientific_name': 'Euphorbia spp.',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'ultra_low',
  'water_frequency': 'Drought-tolerant once established',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Drought-tolerant native',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Euphorbia'},
 {'name': 'False Banana',
  'scientific_name': 'Garcinia kola',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['partial'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['native'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=False+Banana'},
 {'name': 'Fennel',
  'scientific_name': 'Foeniculum vulgare',
  'climate_zones': ['mediterranean'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Mediterranean native',
  'image_url': 'https://placehold.co/640x480/7a8a5c/ffffff.png?text=Fennel'},
 {'name': 'Ficus (Fig tree)',
  'scientific_name': 'Ficus benjamina',
  'climate_zones': ['tropical_rainforest'],
  'sun_exposure': ['full_sun', 'partial'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['humid-loving'],
  'care_tips': [],
  'impact_label': 'Rainforest species',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=Ficus+%28Fig+tree%29'},
 {'name': 'Fig Tree',
  'scientific_name': 'Ficus carica',
  'climate_zones': ['mediterranean'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Mediterranean native',
  'image_url': 'https://placehold.co/640x480/7a8a5c/ffffff.png?text=Fig+Tree'},
 {'name': 'Flame Lily',
  'scientific_name': 'Pterocarpus soyauxii',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy', 'sandy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Flame+Lily'},
 {'name': 'Flax',
  'scientific_name': 'Linum usitatissimum',
  'climate_zones': ['temperate'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Temperate native',
  'image_url': 'https://placehold.co/640x480/5a8a7a/ffffff.png?text=Flax'},
 {'name': 'Frangipani (Plumeria)',
  'scientific_name': 'Plumeria rubra',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Frangipani+%28Plumeria%29'},
 {'name': 'Garden egg (African eggplant)',
  'scientific_name': 'Solanum aethiopicum',
  'climate_zones': ['tropical_rainforest'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Rainforest species',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=Garden+egg+%28African+eggplant%29'},
 {'name': 'Garlic',
  'scientific_name': 'Allium sativum',
  'climate_zones': ['temperate', 'tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Rainforest species',
  'image_url': 'https://placehold.co/640x480/5a8a7a/ffffff.png?text=Garlic'},
 {'name': 'Giant Groundsel',
  'scientific_name': 'Treculia africana',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['partial'],
  'soil_types': ['loamy'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['native'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Giant+Groundsel'},
 {'name': 'Ginger',
  'scientific_name': 'Zingiber officinale',
  'climate_zones': ['tropical_rainforest'],
  'sun_exposure': ['partial'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['humid-loving'],
  'care_tips': [],
  'impact_label': 'Rainforest species',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=Ginger'},
 {'name': 'Grains of Paradise',
  'scientific_name': 'Guibourtia tessmannii',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Grains+of+Paradise'},
 {'name': 'Grapevine',
  'scientific_name': 'Vitis vinifera',
  'climate_zones': ['mediterranean'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Mediterranean native',
  'image_url': 'https://placehold.co/640x480/7a8a5c/ffffff.png?text=Grapevine'},
 {'name': 'Grevillea',
  'scientific_name': 'Grevillea robusta',
  'climate_zones': ['arid_semi_arid', 'tropical_highland', 'tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Grevillea'},
 {'name': 'Henna',
  'scientific_name': 'Lawsonia inermis',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Henna'},
 {'name': 'Hibiscus',
  'scientific_name': 'Hibiscus rosa-sinensis',
  'climate_zones': ['tropical_rainforest'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Rainforest species',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=Hibiscus'},
 {'name': 'Ixora',
  'scientific_name': 'Ixora coccinea',
  'climate_zones': ['tropical_rainforest'],
  'sun_exposure': ['full_sun', 'partial'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['humid-loving'],
  'care_tips': [],
  'impact_label': 'Rainforest species',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=Ixora'},
 {'name': 'Juniper',
  'scientific_name': 'Juniperus phoenicea',
  'climate_zones': ['tropical_highland'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/4a7c4e/ffffff.png?text=Juniper'},
 {'name': 'Katemfe (Aframomum melegueta)',
  'scientific_name': 'Aframomum melegueta',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['shade'],
  'soil_types': ['peat'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['shade-tolerant'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Katemfe'},
 {'name': 'Katemfe (Vitellaria paradoxa)',
  'scientific_name': 'Vitellaria paradoxa',
  'climate_zones': ['arid_semi_arid', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['lateritic_red_clay', 'sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Katemfe'},
 {'name': 'Kola Nut (Lovoa trichilioides)',
  'scientific_name': 'Lovoa trichilioides',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Kola+Nut'},
 {'name': 'Kola Nut (Tamarindus indica)',
  'scientific_name': 'Tamarindus indica',
  'climate_zones': ['arid_semi_arid', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['clay', 'sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Kola+Nut'},
 {'name': 'Lagos Rubber Tree',
  'scientific_name': 'Borassus aethiopum',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Lagos+Rubber+Tree'},
 {'name': 'Lavender',
  'scientific_name': 'Lavandula spp.',
  'climate_zones': ['mediterranean'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Mediterranean native',
  'image_url': 'https://placehold.co/640x480/7a8a5c/ffffff.png?text=Lavender'},
 {'name': 'Lemon',
  'scientific_name': 'Citrus limon',
  'climate_zones': ['mediterranean'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/7a8a5c/ffffff.png?text=Lemon'},
 {'name': 'Lemongrass',
  'scientific_name': 'Cymbopogon citratus',
  'climate_zones': ['tropical_highland', 'tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Rainforest species',
  'image_url': 'https://placehold.co/640x480/4a7c4e/ffffff.png?text=Lemongrass'},
 {'name': 'Lentil',
  'scientific_name': 'Lens culinaris',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Lentil'},
 {'name': 'Leopard Orchid',
  'scientific_name': 'Musanga cecropioides',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['peat'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Leopard+Orchid'},
 {'name': 'Lettuce',
  'scientific_name': 'Lactuca sativa',
  'climate_zones': ['temperate'],
  'sun_exposure': ['partial'],
  'soil_types': ['loamy'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['native'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/5a8a7a/ffffff.png?text=Lettuce'},
 {'name': 'Limba (Fraké)',
  'scientific_name': 'Monodora myristica',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['partial'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['native'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Limba+%28Frak%C3%A9%29'},
 {'name': 'Lotus',
  'scientific_name': 'Nelumbo nucifera',
  'climate_zones': ['tropical_rainforest'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['clay'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=Lotus'},
 {'name': 'Mahogany',
  'scientific_name': 'Khaya senegalensis',
  'climate_zones': ['tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Rainforest species',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=Mahogany'},
 {'name': 'Maize',
  'scientific_name': 'Zea mays',
  'climate_zones': ['arid_semi_arid', 'tropical_highland', 'tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Maize'},
 {'name': 'Mango',
  'scientific_name': 'Mangifera indica',
  'climate_zones': ['arid_semi_arid', 'tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy', 'sandy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Mango'},
 {'name': 'Mangrove (limited)',
  'scientific_name': 'Avicennia marina',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Mangrove+%28limited%29'},
 {'name': 'Millet',
  'scientific_name': 'Pennisetum glaucum',
  'climate_zones': ['arid_semi_arid', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Millet'},
 {'name': 'Mint',
  'scientific_name': 'Mentha spp.',
  'climate_zones': ['temperate'],
  'sun_exposure': ['partial'],
  'soil_types': ['loamy'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['native'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/5a8a7a/ffffff.png?text=Mint'},
 {'name': 'Miracle Berry',
  'scientific_name': 'Thaumatococcus daniellii',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['shade'],
  'soil_types': ['peat'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['shade-tolerant'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Miracle+Berry'},
 {'name': 'Moabi (Nauclea latifolia)',
  'scientific_name': 'Nauclea latifolia',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy', 'sandy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Moabi'},
 {'name': 'Moabi (Spathodea campanulata)',
  'scientific_name': 'Spathodea campanulata',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy', 'sandy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Moabi'},
 {'name': 'Moringa',
  'scientific_name': 'Moringa oleifera',
  'climate_zones': ['arid_semi_arid', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy', 'sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Moringa'},
 {'name': 'Neem Tree',
  'scientific_name': 'Azadirachta indica',
  'climate_zones': ['arid_semi_arid', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy', 'sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Neem+Tree'},
 {'name': 'Njansang (Agapanthus africanus)',
  'scientific_name': 'Agapanthus africanus',
  'climate_zones': ['temperate', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy', 'sandy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Temperate native',
  'image_url': 'https://placehold.co/640x480/5a8a7a/ffffff.png?text=Njansang'},
 {'name': 'Njansang (Dendrosenecio adnivalis)',
  'scientific_name': 'Dendrosenecio adnivalis',
  'climate_zones': ['tropical_highland'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['peat'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/4a7c4e/ffffff.png?text=Njansang'},
 {'name': 'Njansang (Oncoba spinosa)',
  'scientific_name': 'Oncoba spinosa',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Njansang'},
 {'name': 'Oil Palm',
  'scientific_name': 'Pistia stratiotes',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Oil+Palm'},
 {'name': 'Okoume',
  'scientific_name': 'Synsepalum dulcificum',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['partial'],
  'soil_types': ['loamy'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['native'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Okoume'},
 {'name': 'Okra',
  'scientific_name': 'Abelmoschus esculentus',
  'climate_zones': ['tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Rainforest species',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=Okra'},
 {'name': 'Oleander',
  'scientific_name': 'Nerium oleander',
  'climate_zones': ['mediterranean'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Mediterranean native',
  'image_url': 'https://placehold.co/640x480/7a8a5c/ffffff.png?text=Oleander'},
 {'name': 'Olive Tree',
  'scientific_name': 'Olea europaea',
  'climate_zones': ['mediterranean'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Mediterranean native',
  'image_url': 'https://placehold.co/640x480/7a8a5c/ffffff.png?text=Olive+Tree'},
 {'name': 'Onion',
  'scientific_name': 'Allium cepa',
  'climate_zones': ['arid_semi_arid', 'temperate', 'tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy', 'sandy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Onion'},
 {'name': 'Orange',
  'scientific_name': 'Citrus sinensis',
  'climate_zones': ['mediterranean'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/7a8a5c/ffffff.png?text=Orange'},
 {'name': 'Papaya',
  'scientific_name': 'Carica papaya',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Papaya'},
 {'name': 'Papyrus',
  'scientific_name': 'Cyperus papyrus',
  'climate_zones': ['tropical_rainforest'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['clay'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=Papyrus'},
 {'name': 'Peach',
  'scientific_name': 'Prunus persica',
  'climate_zones': ['mediterranean'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Mediterranean native',
  'image_url': 'https://placehold.co/640x480/7a8a5c/ffffff.png?text=Peach'},
 {'name': 'Pepper (Chili pepper)',
  'scientific_name': 'Capsicum annuum',
  'climate_zones': ['tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Rainforest species',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=Pepper+%28Chili+pepper%29'},
 {'name': 'Pineapple',
  'scientific_name': 'Ananas comosus',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Pineapple'},
 {'name': 'Plantain',
  'scientific_name': 'Musa paradisiaca',
  'climate_zones': ['tropical_rainforest'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Rainforest species',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=Plantain'},
 {'name': 'Pomegranate',
  'scientific_name': 'Punica granatum',
  'climate_zones': ['mediterranean'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Mediterranean native',
  'image_url': 'https://placehold.co/640x480/7a8a5c/ffffff.png?text=Pomegranate'},
 {'name': 'Prickly Pear',
  'scientific_name': 'Opuntia ficus-indica',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'ultra_low',
  'water_frequency': 'Drought-tolerant once established',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Drought-tolerant native',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Prickly+Pear'},
 {'name': 'Raffia Palm',
  'scientific_name': 'Funtumia elastica',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Raffia+Palm'},
 {'name': 'Red Ironwood (Azobé) (Dialium guineense)',
  'scientific_name': 'Dialium guineense',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy', 'sandy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Red+Ironwood+%28Azob%C3%A9%29'},
 {'name': 'Red Ironwood (Azobé) (Gardenia ternifolia)',
  'scientific_name': 'Gardenia ternifolia',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Red+Ironwood+%28Azob%C3%A9%29'},
 {'name': 'Reed Grass',
  'scientific_name': 'Phragmites australis',
  'climate_zones': ['tropical_rainforest'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['clay'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=Reed+Grass'},
 {'name': 'Retama Broom',
  'scientific_name': 'Retama raetam',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'ultra_low',
  'water_frequency': 'Drought-tolerant once established',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Drought-tolerant native',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Retama+Broom'},
 {'name': 'Rice',
  'scientific_name': 'Oryza sativa',
  'climate_zones': ['tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['clay', 'loamy', 'peat'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=Rice'},
 {'name': 'Rosemary',
  'scientific_name': 'Rosmarinus officinalis',
  'climate_zones': ['mediterranean'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Mediterranean native',
  'image_url': 'https://placehold.co/640x480/7a8a5c/ffffff.png?text=Rosemary'},
 {'name': 'Rubber tree',
  'scientific_name': 'Hevea brasiliensis',
  'climate_zones': ['tropical_rainforest'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy', 'sandy'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=Rubber+tree'},
 {'name': 'Sage',
  'scientific_name': 'Salvia officinalis',
  'climate_zones': ['mediterranean'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Mediterranean native',
  'image_url': 'https://placehold.co/640x480/7a8a5c/ffffff.png?text=Sage'},
 {'name': 'Saharan Cypress',
  'scientific_name': 'Cupressus dupreziana',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'ultra_low',
  'water_frequency': 'Drought-tolerant once established',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Drought-tolerant native',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Saharan+Cypress'},
 {'name': 'Saltbush',
  'scientific_name': 'Atriplex halimus',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Saltbush'},
 {'name': 'Sapele (Aframomum angustifolium)',
  'scientific_name': 'Aframomum angustifolium',
  'climate_zones': ['tropical_highland', 'tropical_savanna'],
  'sun_exposure': ['shade'],
  'soil_types': ['peat'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['shade-tolerant'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/4a7c4e/ffffff.png?text=Sapele'},
 {'name': 'Sapele (Pycnanthus angolensis)',
  'scientific_name': 'Pycnanthus angolensis',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy', 'peat'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Sapele'},
 {'name': 'Sea Rush',
  'scientific_name': 'Juncus maritimus',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Sea+Rush'},
 {'name': 'Sesame (Beni-seed) (Afrocarpus falcatus)',
  'scientific_name': 'Afrocarpus falcatus',
  'climate_zones': ['tropical_highland'],
  'sun_exposure': ['partial'],
  'soil_types': ['peat'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['native'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/4a7c4e/ffffff.png?text=Sesame+%28Beni-seed%29'},
 {'name': 'Sesame (Beni-seed) (Mimusops zeyheri)',
  'scientific_name': 'Mimusops zeyheri',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Sesame+%28Beni-seed%29'},
 {'name': 'Shea Butter Tree',
  'scientific_name': 'Ansellia africana',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['partial'],
  'soil_types': ['peat'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['native'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Shea+Butter+Tree'},
 {'name': 'Sorghum',
  'scientific_name': 'Sorghum bicolor',
  'climate_zones': ['arid_semi_arid', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy', 'sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Sorghum'},
 {'name': 'Spinach',
  'scientific_name': 'Spinacia oleracea',
  'climate_zones': ['temperate'],
  'sun_exposure': ['partial'],
  'soil_types': ['loamy'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['native'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/5a8a7a/ffffff.png?text=Spinach'},
 {'name': 'Spinach (Amaranth)',
  'scientific_name': 'Amaranthus hybridus',
  'climate_zones': ['tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun', 'partial'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['humid-loving'],
  'care_tips': [],
  'impact_label': 'Rainforest species',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=Spinach+%28Amaranth%29'},
 {'name': 'Stone Pine',
  'scientific_name': 'Pinus pinea',
  'climate_zones': ['mediterranean'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Mediterranean native',
  'image_url': 'https://placehold.co/640x480/7a8a5c/ffffff.png?text=Stone+Pine'},
 {'name': 'Sunflower',
  'scientific_name': 'Helianthus annuus',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Sunflower'},
 {'name': 'Tamarisk (Tamarix senegalensis)',
  'scientific_name': 'Tamarix senegalensis',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Tamarisk'},
 {'name': 'Tamarisk (Tamarix spp.)',
  'scientific_name': 'Tamarix spp.',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Tamarisk'},
 {'name': 'Tea Plant',
  'scientific_name': 'Camellia sinensis',
  'climate_zones': ['tropical_highland'],
  'sun_exposure': ['partial'],
  'soil_types': ['loamy'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['native'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/4a7c4e/ffffff.png?text=Tea+Plant'},
 {'name': 'Thyme',
  'scientific_name': 'Thymus vulgaris',
  'climate_zones': ['mediterranean'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Mediterranean native',
  'image_url': 'https://placehold.co/640x480/7a8a5c/ffffff.png?text=Thyme'},
 {'name': 'Tomato',
  'scientific_name': 'Solanum lycopersicum',
  'climate_zones': ['tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Rainforest species',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=Tomato'},
 {'name': 'Umbrella Tree',
  'scientific_name': 'Gloriosa superba',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy', 'sandy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Umbrella+Tree'},
 {'name': 'Velvet Tamarind',
  'scientific_name': 'Dioscorea rotundata',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Velvet+Tamarind'},
 {'name': 'Water Lettuce',
  'scientific_name': 'Vigna subterranea',
  'climate_zones': ['arid_semi_arid', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Dryland survivor',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=Water+Lettuce'},
 {'name': 'Water Lily',
  'scientific_name': 'Nymphaea lotus',
  'climate_zones': ['tropical_rainforest'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['clay'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=Water+Lily'},
 {'name': 'Wenge (Ensete ventricosum)',
  'scientific_name': 'Ensete ventricosum',
  'climate_zones': ['tropical_highland'],
  'sun_exposure': ['partial'],
  'soil_types': ['peat'],
  'water_conservation': 'high',
  'water_frequency': 'Keep consistently moist',
  'tags': ['native'],
  'care_tips': [],
  'impact_label': 'Lush growth',
  'image_url': 'https://placehold.co/640x480/4a7c4e/ffffff.png?text=Wenge'},
 {'name': 'Wenge (Eulophia guineensis)',
  'scientific_name': 'Eulophia guineensis',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['shade'],
  'soil_types': ['peat'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['shade-tolerant'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Wenge'},
 {'name': 'Wheat',
  'scientific_name': 'Triticum aestivum',
  'climate_zones': ['mediterranean'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving'],
  'care_tips': [],
  'impact_label': 'Mediterranean native',
  'image_url': 'https://placehold.co/640x480/7a8a5c/ffffff.png?text=Wheat'},
 {'name': 'White Guinea Yam',
  'scientific_name': 'Sesamum indicum',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=White+Guinea+Yam'},
 {'name': 'White Wormwood',
  'scientific_name': 'Artemisia herba-alba',
  'climate_zones': ['arid_semi_arid'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'ultra_low',
  'water_frequency': 'Drought-tolerant once established',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Drought-tolerant native',
  'image_url': 'https://placehold.co/640x480/c4a574/ffffff.png?text=White+Wormwood'},
 {'name': 'Wild Ginger',
  'scientific_name': 'Scadoxus multiflorus',
  'climate_zones': ['tropical_savanna'],
  'sun_exposure': ['partial'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['native'],
  'care_tips': [],
  'impact_label': 'Native African plant',
  'image_url': 'https://placehold.co/640x480/8b9d4a/ffffff.png?text=Wild+Ginger'},
 {'name': 'Wild Olive (Olea europaea var. sylvestris)',
  'scientific_name': 'Olea europaea var. sylvestris',
  'climate_zones': ['mediterranean'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Mediterranean native',
  'image_url': 'https://placehold.co/640x480/7a8a5c/ffffff.png?text=Wild+Olive'},
 {'name': 'Wild Olive (Olea europaea var.)',
  'scientific_name': 'Olea europaea var.',
  'climate_zones': ['mediterranean'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['sandy'],
  'water_conservation': 'low',
  'water_frequency': 'Every 1-2 weeks',
  'tags': ['drought-tolerant', 'sun-loving'],
  'care_tips': [],
  'impact_label': 'Mediterranean native',
  'image_url': 'https://placehold.co/640x480/7a8a5c/ffffff.png?text=Wild+Olive'},
 {'name': 'Yam',
  'scientific_name': 'Dioscorea spp.',
  'climate_zones': ['tropical_rainforest', 'tropical_savanna'],
  'sun_exposure': ['full_sun'],
  'soil_types': ['loamy'],
  'water_conservation': 'moderate',
  'water_frequency': 'Twice weekly',
  'tags': ['sun-loving', 'humid-loving'],
  'care_tips': [],
  'impact_label': 'Rainforest species',
  'image_url': 'https://placehold.co/640x480/2d5a2f/ffffff.png?text=Yam'}]


class Command(BaseCommand):
    help = "Seed the Plant catalogue with native African flora."

    def add_arguments(self, parser):
        parser.add_argument(
            "--reset",
            action="store_true",
            help="Delete all existing plants before seeding.",
        )

    def handle(self, *args, **options):
        if options.get("reset"):
            deleted, _ = Plant.objects.all().delete()
            self.stdout.write(self.style.WARNING(
                f"Reset: deleted {deleted} existing plant row(s)."
            ))

        created = 0
        for entry in SAMPLE_PLANTS:
            _, was_created = Plant.objects.get_or_create(
                scientific_name=entry["scientific_name"],
                defaults=entry,
            )
            if was_created:
                created += 1

        self.stdout.write(self.style.SUCCESS(
            f"Seeded {created} new plant(s). Total catalogue: {Plant.objects.count()}."
        ))
