"""
Management command: python manage.py seed_plants

Populates the Plant catalogue with native African flora across all climate
zones, sun levels, soils, and water-conservation profiles so Green Match
returns varied recommendations for different user inputs.

The catalogue is deliberately diverse — many plants are narrow in their
preferences (e.g. shade-only, peat-only) so different inputs surface
different top matches. Re-running this command is idempotent.
"""
from django.core.management.base import BaseCommand
from apps.plants.models import Plant


SAMPLE_PLANTS = [
    # ------------------------------------------------------------------
    # TROPICAL SAVANNA / ARID — drought-tolerant, full sun, sandy/loamy
    # ------------------------------------------------------------------
    {
        'name': 'Baobab',
        'scientific_name': 'Adansonia digitata',
        'climate_zones': ['tropical_savanna', 'arid_semi_arid'],
        'sun_exposure': ['full_sun'],
        'soil_types': ['sandy', 'loamy', 'lateritic_red_clay'],
        'water_conservation': 'ultra_low',
        'water_frequency': 'Drought-tolerant once established',
        'tags': ['iconic', 'drought-tolerant', 'long-lived'],
        'care_tips': [
            'Plant in well-drained soil',
            'Water sparingly in the first year, then leave alone',
            'Prune dead branches at the start of the rainy season',
        ],
        'impact_label': 'Carbon-storing giant',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Baobab_and_elephants.jpg/640px-Baobab_and_elephants.jpg',
    },
    {
        'name': 'Acacia',
        'scientific_name': 'Vachellia tortilis',
        'climate_zones': ['tropical_savanna', 'arid_semi_arid'],
        'sun_exposure': ['full_sun'],
        'soil_types': ['sandy', 'lateritic_red_clay'],
        'water_conservation': 'ultra_low',
        'water_frequency': 'Rainfall is enough once established',
        'tags': ['nitrogen-fixing', 'wildlife-friendly', 'iconic'],
        'care_tips': [
            'Provide deep watering for the first 6 months',
            'Plant away from foundations — taproots run deep',
            'No fertiliser needed; fixes its own nitrogen',
        ],
        'impact_label': 'Soil enricher',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Vachellia_tortilis_-_acacia.jpg/640px-Vachellia_tortilis_-_acacia.jpg',
    },
    {
        'name': 'Marula',
        'scientific_name': 'Sclerocarya birrea',
        'climate_zones': ['tropical_savanna', 'arid_semi_arid'],
        'sun_exposure': ['full_sun'],
        'soil_types': ['sandy', 'loamy'],
        'water_conservation': 'ultra_low',
        'water_frequency': 'Once established, only during droughts',
        'tags': ['fruit-bearing', 'wildlife-friendly', 'drought-tolerant'],
        'care_tips': [
            'Plant in deep, well-drained soil',
            'Allow space — mature trees reach 18m',
            'Harvest fallen fruit; do not pick from tree',
        ],
        'impact_label': 'Fruit-bearing native',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Sclerocarya_birrea_tree.jpg/640px-Sclerocarya_birrea_tree.jpg',
    },
    {
        'name': 'African Wild Olive',
        'scientific_name': 'Olea europaea subsp. cuspidata',
        'climate_zones': ['tropical_savanna', 'mediterranean', 'tropical_highland'],
        'sun_exposure': ['full_sun'],
        'soil_types': ['loamy', 'sandy', 'clay'],
        'water_conservation': 'low',
        'water_frequency': 'Monthly once established',
        'tags': ['evergreen', 'drought-tolerant', 'edible'],
        'care_tips': [
            'Tolerates poor soils but needs good drainage',
            'Prune annually to maintain shape',
            'Wildlife love the small fruits',
        ],
        'impact_label': 'Hardy evergreen',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Olea_europaea_subsp_cuspidata.jpg/640px-Olea_europaea_subsp_cuspidata.jpg',
    },
    {
        'name': 'Sausage Tree',
        'scientific_name': 'Kigelia africana',
        'climate_zones': ['tropical_savanna', 'tropical_rainforest'],
        'sun_exposure': ['full_sun', 'partial'],
        'soil_types': ['loamy', 'clay', 'lateritic_red_clay'],
        'water_conservation': 'low',
        'water_frequency': 'Weekly during dry spells',
        'tags': ['shade-tree', 'wildlife-friendly', 'medicinal'],
        'care_tips': [
            'Allow plenty of space — mature trees are large',
            'Water deeply during establishment',
            'Falling fruit is heavy — avoid planting near walkways',
        ],
        'impact_label': 'Wildlife habitat',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Kigelia_africana_MS_4276.JPG/640px-Kigelia_africana_MS_4276.JPG',
    },
    {
        'name': 'Moringa',
        'scientific_name': 'Moringa oleifera',
        'climate_zones': ['tropical_savanna', 'arid_semi_arid', 'tropical_rainforest'],
        'sun_exposure': ['full_sun'],
        'soil_types': ['sandy', 'loamy', 'lateritic_red_clay'],
        'water_conservation': 'low',
        'water_frequency': 'Weekly when young; biweekly when established',
        'tags': ['nutritious', 'fast-growing', 'medicinal'],
        'care_tips': [
            'Plant from seed directly in the ground',
            'Pinch top to encourage bushy growth',
            'Harvest leaves regularly for nutrition',
        ],
        'impact_label': 'Nutrition powerhouse',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Starr_080117-1612_Moringa_oleifera.jpg/640px-Starr_080117-1612_Moringa_oleifera.jpg',
    },
    {
        'name': 'Sickle Bush',
        'scientific_name': 'Dichrostachys cinerea',
        'climate_zones': ['tropical_savanna', 'arid_semi_arid'],
        'sun_exposure': ['full_sun'],
        'soil_types': ['sandy', 'lateritic_red_clay', 'clay'],
        'water_conservation': 'ultra_low',
        'water_frequency': 'Rainfall sufficient',
        'tags': ['nitrogen-fixing', 'thorny', 'pioneer-species'],
        'care_tips': [
            'Excellent for degraded land restoration',
            'Spreads aggressively — manage with care',
            'Good livestock fodder',
        ],
        'impact_label': 'Land restorer',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Dichrostachys_cinerea1.jpg/640px-Dichrostachys_cinerea1.jpg',
    },

    # ------------------------------------------------------------------
    # ARID / SEMI-ARID — succulents and desert specialists
    # ------------------------------------------------------------------
    {
        'name': 'Aloe Vera',
        'scientific_name': 'Aloe barbadensis miller',
        'climate_zones': ['arid_semi_arid', 'mediterranean', 'tropical_savanna'],
        'sun_exposure': ['full_sun', 'partial'],
        'soil_types': ['sandy', 'loamy'],
        'water_conservation': 'ultra_low',
        'water_frequency': 'Every 2-3 weeks',
        'tags': ['medicinal', 'drought-tolerant', 'low-maintenance'],
        'care_tips': [
            'Use a sandy, fast-draining soil mix',
            'Let soil dry completely between waterings',
            'Bring indoors if temperatures drop below 10°C',
        ],
        'impact_label': 'Water-wise medicinal',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Aloe_vera_flower.jpg/640px-Aloe_vera_flower.jpg',
    },
    {
        'name': 'Spekboom',
        'scientific_name': 'Portulacaria afra',
        'climate_zones': ['arid_semi_arid', 'mediterranean', 'tropical_savanna'],
        'sun_exposure': ['full_sun', 'partial'],
        'soil_types': ['sandy', 'loamy'],
        'water_conservation': 'ultra_low',
        'water_frequency': 'Every 2-4 weeks',
        'tags': ['carbon-sequestering', 'edible', 'drought-tolerant'],
        'care_tips': [
            'Propagates easily from cuttings',
            'Avoid overwatering — roots rot quickly',
            'Excellent ground cover for slopes',
        ],
        'impact_label': 'Carbon-sequestering champion',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Portulacaria_afra1.jpg/640px-Portulacaria_afra1.jpg',
    },
    {
        'name': 'Quiver Tree',
        'scientific_name': 'Aloidendron dichotomum',
        'climate_zones': ['arid_semi_arid'],
        'sun_exposure': ['full_sun'],
        'soil_types': ['sandy', 'lateritic_red_clay'],
        'water_conservation': 'ultra_low',
        'water_frequency': 'Almost never once established',
        'tags': ['iconic', 'desert-specialist', 'slow-growing'],
        'care_tips': [
            'Needs sharp drainage — never waterlog',
            'Full sun all day, no shade',
            'Tolerates extreme heat',
        ],
        'impact_label': 'Desert sentinel',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Aloidendron_dichotomum.jpg/640px-Aloidendron_dichotomum.jpg',
    },
    {
        'name': 'Desert Date',
        'scientific_name': 'Balanites aegyptiaca',
        'climate_zones': ['arid_semi_arid', 'tropical_savanna'],
        'sun_exposure': ['full_sun'],
        'soil_types': ['sandy', 'loamy'],
        'water_conservation': 'ultra_low',
        'water_frequency': 'Rainfall only',
        'tags': ['edible', 'medicinal', 'thorny'],
        'care_tips': [
            'Tolerates extreme drought',
            'Fruits and oil are edible',
            'Slow but steady growth',
        ],
        'impact_label': 'Desert food source',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Balanites_aegyptiaca_MS_4255.JPG/640px-Balanites_aegyptiaca_MS_4255.JPG',
    },
    {
        'name': 'Hoodia',
        'scientific_name': 'Hoodia gordonii',
        'climate_zones': ['arid_semi_arid'],
        'sun_exposure': ['full_sun'],
        'soil_types': ['sandy'],
        'water_conservation': 'ultra_low',
        'water_frequency': 'Almost none',
        'tags': ['succulent', 'medicinal', 'rare'],
        'care_tips': [
            'Sandy, gritty soil only',
            'Water sparingly even in summer',
            'Protect from frost',
        ],
        'impact_label': 'Endemic succulent',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Hoodia_gordonii.jpg/640px-Hoodia_gordonii.jpg',
    },

    # ------------------------------------------------------------------
    # TROPICAL HIGHLAND — Kenya, Ethiopia, Rwanda, Uganda
    # ------------------------------------------------------------------
    {
        'name': 'African Violet',
        'scientific_name': 'Saintpaulia ionantha',
        'climate_zones': ['tropical_highland', 'tropical_rainforest'],
        'sun_exposure': ['partial', 'shade'],
        'soil_types': ['loamy', 'peat'],
        'water_conservation': 'moderate',
        'water_frequency': 'When top of soil feels dry',
        'tags': ['ornamental', 'indoor', 'flowering'],
        'care_tips': [
            'Water from below to avoid leaf spotting',
            'Keep in bright, indirect light',
            'Maintain humidity above 50%',
        ],
        'impact_label': 'Native ornamental',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Saintpaulia_ionantha.jpg/640px-Saintpaulia_ionantha.jpg',
    },
    {
        'name': 'Coffee Arabica',
        'scientific_name': 'Coffea arabica',
        'climate_zones': ['tropical_highland'],
        'sun_exposure': ['partial'],
        'soil_types': ['loamy', 'lateritic_red_clay'],
        'water_conservation': 'moderate',
        'water_frequency': 'Twice weekly during dry season',
        'tags': ['edible', 'cash-crop', 'shade-loving'],
        'care_tips': [
            'Plant under taller shade trees',
            'Mulch heavily to retain moisture',
            'Harvest cherries when bright red',
        ],
        'impact_label': 'Highland cash crop',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Coffea_arabica_-_Köhler–s_Medizinal-Pflanzen-189.jpg/640px-Coffea_arabica_-_Köhler–s_Medizinal-Pflanzen-189.jpg',
    },
    {
        'name': 'Ensete',
        'scientific_name': 'Ensete ventricosum',
        'climate_zones': ['tropical_highland', 'tropical_rainforest'],
        'sun_exposure': ['full_sun', 'partial'],
        'soil_types': ['loamy', 'lateritic_red_clay'],
        'water_conservation': 'moderate',
        'water_frequency': 'Twice weekly',
        'tags': ['edible', 'staple-food', 'fast-growing'],
        'care_tips': [
            'Rich, deep soil for best growth',
            'Protect from strong winds',
            'Harvest stems for traditional dishes',
        ],
        'impact_label': 'Food security crop',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Ensete_ventricosum.jpg/640px-Ensete_ventricosum.jpg',
    },
    {
        'name': 'Kikuyu Grass',
        'scientific_name': 'Cenchrus clandestinus',
        'climate_zones': ['tropical_highland', 'tropical_savanna'],
        'sun_exposure': ['full_sun', 'partial'],
        'soil_types': ['loamy', 'clay', 'lateritic_red_clay'],
        'water_conservation': 'low',
        'water_frequency': 'Weekly',
        'tags': ['ground-cover', 'erosion-control', 'fast-spreading'],
        'care_tips': [
            'Mow regularly to prevent invasiveness',
            'Excellent for slopes and lawns',
            'Tolerates foot traffic well',
        ],
        'impact_label': 'Erosion control',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Cenchrus_clandestinus.jpg/640px-Cenchrus_clandestinus.jpg',
    },
    {
        'name': 'African Marigold',
        'scientific_name': 'Tagetes erecta',
        'climate_zones': ['tropical_savanna', 'tropical_highland', 'mediterranean'],
        'sun_exposure': ['full_sun'],
        'soil_types': ['loamy', 'sandy', 'clay'],
        'water_conservation': 'moderate',
        'water_frequency': 'Twice a week',
        'tags': ['pest-repellent', 'flowering', 'companion-plant'],
        'care_tips': [
            'Deadhead spent blooms to prolong flowering',
            'Plant near vegetables to deter aphids',
            'Tolerates poor soils',
        ],
        'impact_label': 'Natural pest deterrent',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Tagetes_erecta1.jpg/640px-Tagetes_erecta1.jpg',
    },
    {
        'name': 'Cape Chestnut',
        'scientific_name': 'Calodendrum capense',
        'climate_zones': ['tropical_highland', 'temperate'],
        'sun_exposure': ['full_sun', 'partial'],
        'soil_types': ['loamy', 'clay'],
        'water_conservation': 'moderate',
        'water_frequency': 'Weekly during dry months',
        'tags': ['flowering', 'shade-tree', 'ornamental'],
        'care_tips': [
            'Best in deep, fertile soil',
            'Spectacular pink blossoms in summer',
            'Allow plenty of room to spread',
        ],
        'impact_label': 'Highland ornamental',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Calodendrum_capense00.jpg/640px-Calodendrum_capense00.jpg',
    },
    {
        'name': 'Pyrethrum Daisy',
        'scientific_name': 'Tanacetum cinerariifolium',
        'climate_zones': ['tropical_highland', 'mediterranean'],
        'sun_exposure': ['full_sun'],
        'soil_types': ['loamy', 'sandy'],
        'water_conservation': 'low',
        'water_frequency': 'Weekly',
        'tags': ['pest-repellent', 'flowering', 'cash-crop'],
        'care_tips': [
            'Needs cool nights to flower well',
            'Harvest flowers fully open',
            'Avoid waterlogged soils',
        ],
        'impact_label': 'Natural insecticide',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Tanacetum_cinerariifolium.jpg/640px-Tanacetum_cinerariifolium.jpg',
    },

    # ------------------------------------------------------------------
    # TROPICAL RAINFOREST — Congo, West Africa, lowland tropics
    # ------------------------------------------------------------------
    {
        'name': 'Cocoa Tree',
        'scientific_name': 'Theobroma cacao',
        'climate_zones': ['tropical_rainforest'],
        'sun_exposure': ['partial', 'shade'],
        'soil_types': ['loamy', 'lateritic_red_clay'],
        'water_conservation': 'moderate',
        'water_frequency': 'Twice weekly',
        'tags': ['edible', 'cash-crop', 'shade-loving'],
        'care_tips': [
            'Needs taller trees overhead for shade',
            'Hates waterlogging — drainage matters',
            'High humidity preferred',
        ],
        'impact_label': 'Forest understory crop',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Cocoa_Pods.JPG/640px-Cocoa_Pods.JPG',
    },
    {
        'name': 'African Mahogany',
        'scientific_name': 'Khaya senegalensis',
        'climate_zones': ['tropical_rainforest', 'tropical_savanna'],
        'sun_exposure': ['full_sun', 'partial'],
        'soil_types': ['loamy', 'lateritic_red_clay'],
        'water_conservation': 'low',
        'water_frequency': 'Weekly during dry season',
        'tags': ['timber', 'shade-tree', 'long-lived'],
        'care_tips': [
            'Plant where it has room — reaches 30m+',
            'Deep watering encourages tap root',
            'Excellent street tree where space allows',
        ],
        'impact_label': 'Sustainable timber',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Khaya_senegalensis_MS_4233.JPG/640px-Khaya_senegalensis_MS_4233.JPG',
    },
    {
        'name': 'Plantain',
        'scientific_name': 'Musa paradisiaca',
        'climate_zones': ['tropical_rainforest', 'tropical_savanna'],
        'sun_exposure': ['full_sun', 'partial'],
        'soil_types': ['loamy', 'peat'],
        'water_conservation': 'moderate',
        'water_frequency': '2-3 times a week',
        'tags': ['edible', 'staple-food', 'fast-growing'],
        'care_tips': [
            'Rich, well-drained soil',
            'Shelter from strong winds',
            'Harvest when fingers fill out',
        ],
        'impact_label': 'Tropical staple',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Plantains.jpg/640px-Plantains.jpg',
    },
    {
        'name': 'Iroko',
        'scientific_name': 'Milicia excelsa',
        'climate_zones': ['tropical_rainforest'],
        'sun_exposure': ['full_sun'],
        'soil_types': ['loamy', 'lateritic_red_clay'],
        'water_conservation': 'low',
        'water_frequency': 'Rainfall is enough',
        'tags': ['timber', 'long-lived', 'sacred'],
        'care_tips': [
            'Needs deep, rich soil',
            'Slow-growing — plan for decades',
            'Wide canopy at maturity',
        ],
        'impact_label': 'Heritage timber tree',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Iroko_tree.jpg/640px-Iroko_tree.jpg',
    },
    {
        'name': 'Wild Ginger',
        'scientific_name': 'Aframomum melegueta',
        'climate_zones': ['tropical_rainforest'],
        'sun_exposure': ['shade', 'partial'],
        'soil_types': ['loamy', 'peat'],
        'water_conservation': 'moderate',
        'water_frequency': 'Keep consistently moist',
        'tags': ['medicinal', 'edible', 'spice'],
        'care_tips': [
            'Loves humid, dappled light',
            'Mulch heavily to retain moisture',
            'Harvest seeds for grains of paradise',
        ],
        'impact_label': 'Forest spice',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Aframomum_melegueta.jpg/640px-Aframomum_melegueta.jpg',
    },
    {
        'name': 'Ackee',
        'scientific_name': 'Blighia sapida',
        'climate_zones': ['tropical_rainforest', 'tropical_savanna'],
        'sun_exposure': ['full_sun', 'partial'],
        'soil_types': ['loamy', 'lateritic_red_clay'],
        'water_conservation': 'moderate',
        'water_frequency': 'Weekly',
        'tags': ['edible', 'fruit-bearing', 'flowering'],
        'care_tips': [
            'Rich, deep soils preferred',
            'Only eat fully ripe arils',
            'Protect young trees from frost',
        ],
        'impact_label': 'West African fruit',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Blighia_sapida_-_Ackee.jpg/640px-Blighia_sapida_-_Ackee.jpg',
    },

    # ------------------------------------------------------------------
    # MEDITERRANEAN — North Africa, Cape region
    # ------------------------------------------------------------------
    {
        'name': 'Olive Tree',
        'scientific_name': 'Olea europaea',
        'climate_zones': ['mediterranean'],
        'sun_exposure': ['full_sun'],
        'soil_types': ['loamy', 'sandy', 'clay'],
        'water_conservation': 'low',
        'water_frequency': 'Monthly once established',
        'tags': ['edible', 'long-lived', 'drought-tolerant'],
        'care_tips': [
            'Excellent drainage essential',
            'Prune for an open vase shape',
            'Tolerates poor, rocky soils',
        ],
        'impact_label': 'Mediterranean staple',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Olive_tree.jpg/640px-Olive_tree.jpg',
    },
    {
        'name': 'Rosemary',
        'scientific_name': 'Salvia rosmarinus',
        'climate_zones': ['mediterranean', 'arid_semi_arid'],
        'sun_exposure': ['full_sun'],
        'soil_types': ['sandy', 'loamy'],
        'water_conservation': 'ultra_low',
        'water_frequency': 'Every 2-3 weeks',
        'tags': ['herb', 'culinary', 'aromatic'],
        'care_tips': [
            'Hates wet feet — sharp drainage',
            'Prune lightly after flowering',
            'Excellent in containers',
        ],
        'impact_label': 'Culinary herb',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Rosemary_bush.jpg/640px-Rosemary_bush.jpg',
    },
    {
        'name': 'Cape Plumbago',
        'scientific_name': 'Plumbago auriculata',
        'climate_zones': ['mediterranean', 'tropical_savanna'],
        'sun_exposure': ['full_sun', 'partial'],
        'soil_types': ['loamy', 'sandy'],
        'water_conservation': 'low',
        'water_frequency': 'Weekly in summer',
        'tags': ['flowering', 'hedge', 'wildlife-friendly'],
        'care_tips': [
            'Prune hard in late winter',
            'Sky-blue flowers from spring to autumn',
            'Tolerates light frost',
        ],
        'impact_label': 'Pollinator magnet',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Plumbago_auriculata_kz1.jpg/640px-Plumbago_auriculata_kz1.jpg',
    },
    {
        'name': 'Cork Oak',
        'scientific_name': 'Quercus suber',
        'climate_zones': ['mediterranean'],
        'sun_exposure': ['full_sun'],
        'soil_types': ['sandy', 'loamy'],
        'water_conservation': 'low',
        'water_frequency': 'Rainfall once established',
        'tags': ['long-lived', 'sustainable-harvest', 'timber'],
        'care_tips': [
            'Acidic, well-drained soils preferred',
            'First cork harvest after 25 years',
            'No pruning once shape is set',
        ],
        'impact_label': 'Renewable cork source',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Quercus_suber.jpg/640px-Quercus_suber.jpg',
    },
    {
        'name': 'Cape Honeysuckle',
        'scientific_name': 'Tecoma capensis',
        'climate_zones': ['mediterranean', 'tropical_savanna'],
        'sun_exposure': ['full_sun', 'partial'],
        'soil_types': ['loamy', 'sandy', 'clay'],
        'water_conservation': 'low',
        'water_frequency': 'Weekly in summer',
        'tags': ['flowering', 'hedge', 'bird-friendly'],
        'care_tips': [
            'Vigorous — prune to control',
            'Attracts sunbirds with orange flowers',
            'Tolerates a wide range of soils',
        ],
        'impact_label': 'Bird habitat',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Tecoma_capensis_kz1.jpg/640px-Tecoma_capensis_kz1.jpg',
    },

    # ------------------------------------------------------------------
    # TEMPERATE — Southern Africa highlands, mountain ranges
    # ------------------------------------------------------------------
    {
        'name': 'Yellowwood',
        'scientific_name': 'Podocarpus latifolius',
        'climate_zones': ['temperate', 'tropical_highland'],
        'sun_exposure': ['full_sun', 'partial'],
        'soil_types': ['loamy', 'peat'],
        'water_conservation': 'moderate',
        'water_frequency': 'Weekly',
        'tags': ['timber', 'long-lived', 'iconic'],
        'care_tips': [
            'Acidic, moisture-retaining soil',
            'Slow but steady — plan ahead',
            'South Africa\'s national tree',
        ],
        'impact_label': 'National heritage tree',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Podocarpus_latifolius.jpg/640px-Podocarpus_latifolius.jpg',
    },
    {
        'name': 'Wild Garlic',
        'scientific_name': 'Tulbaghia violacea',
        'climate_zones': ['temperate', 'mediterranean', 'tropical_highland'],
        'sun_exposure': ['full_sun', 'partial'],
        'soil_types': ['loamy', 'sandy'],
        'water_conservation': 'low',
        'water_frequency': 'Weekly in summer',
        'tags': ['edible', 'pest-repellent', 'flowering'],
        'care_tips': [
            'Splits easily for propagation',
            'Repels moles and aphids',
            'Edible flowers and leaves',
        ],
        'impact_label': 'Edible ornamental',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Tulbaghia_violacea_kz1.jpg/640px-Tulbaghia_violacea_kz1.jpg',
    },
    {
        'name': 'Protea',
        'scientific_name': 'Protea cynaroides',
        'climate_zones': ['temperate', 'mediterranean'],
        'sun_exposure': ['full_sun'],
        'soil_types': ['sandy'],
        'water_conservation': 'low',
        'water_frequency': 'Twice monthly',
        'tags': ['flowering', 'iconic', 'pollinator'],
        'care_tips': [
            'Acidic, sandy soil only — never fertilise',
            'Excellent drainage critical',
            'Prune lightly after flowering',
        ],
        'impact_label': 'Iconic Cape flower',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Protea_cynaroides.jpg/640px-Protea_cynaroides.jpg',
    },
    {
        'name': 'Cape Fynbos Restio',
        'scientific_name': 'Elegia capensis',
        'climate_zones': ['temperate', 'mediterranean'],
        'sun_exposure': ['full_sun'],
        'soil_types': ['sandy', 'peat'],
        'water_conservation': 'moderate',
        'water_frequency': 'Weekly',
        'tags': ['ornamental', 'wetland', 'native'],
        'care_tips': [
            'Tolerates seasonally wet feet',
            'Striking architectural form',
            'Excellent erosion control near water',
        ],
        'impact_label': 'Fynbos specialist',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Elegia_capensis.jpg/640px-Elegia_capensis.jpg',
    },

    # ------------------------------------------------------------------
    # SHADE / PARTIAL — for "shade" sun_exposure inputs
    # ------------------------------------------------------------------
    {
        'name': 'Bird\'s Nest Fern',
        'scientific_name': 'Asplenium nidus',
        'climate_zones': ['tropical_rainforest', 'tropical_highland'],
        'sun_exposure': ['shade', 'partial'],
        'soil_types': ['peat', 'loamy'],
        'water_conservation': 'moderate',
        'water_frequency': 'Keep consistently moist',
        'tags': ['ornamental', 'indoor', 'air-purifier'],
        'care_tips': [
            'High humidity preferred',
            'Avoid water in the central rosette',
            'Filtered light only',
        ],
        'impact_label': 'Indoor air purifier',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Asplenium_nidus_kz1.jpg/640px-Asplenium_nidus_kz1.jpg',
    },
    {
        'name': 'Forest Lily',
        'scientific_name': 'Veltheimia bracteata',
        'climate_zones': ['temperate', 'mediterranean'],
        'sun_exposure': ['shade', 'partial'],
        'soil_types': ['loamy', 'peat'],
        'water_conservation': 'moderate',
        'water_frequency': 'Weekly during growing season',
        'tags': ['flowering', 'shade-loving', 'ornamental'],
        'care_tips': [
            'Plant in dappled shade',
            'Pink flower spikes in winter',
            'Keep dry in summer dormancy',
        ],
        'impact_label': 'Shade-garden gem',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Veltheimia_bracteata.jpg/640px-Veltheimia_bracteata.jpg',
    },
    {
        'name': 'Plectranthus',
        'scientific_name': 'Plectranthus ecklonii',
        'climate_zones': ['tropical_highland', 'temperate'],
        'sun_exposure': ['shade', 'partial'],
        'soil_types': ['loamy', 'peat'],
        'water_conservation': 'moderate',
        'water_frequency': 'Twice weekly',
        'tags': ['flowering', 'shade-loving', 'fast-growing'],
        'care_tips': [
            'Cuts back hard each spring',
            'Purple flower spikes in autumn',
            'Excellent under-tree planting',
        ],
        'impact_label': 'Shade understory',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Plectranthus_ecklonii.jpg/640px-Plectranthus_ecklonii.jpg',
    },
    {
        'name': 'Wild Iris',
        'scientific_name': 'Dietes grandiflora',
        'climate_zones': ['temperate', 'tropical_savanna', 'mediterranean'],
        'sun_exposure': ['partial', 'shade'],
        'soil_types': ['clay', 'loamy'],
        'water_conservation': 'low',
        'water_frequency': 'Twice monthly',
        'tags': ['flowering', 'low-maintenance', 'evergreen'],
        'care_tips': [
            'Tolerates almost any soil',
            'Divide clumps every 3-4 years',
            'White flowers with yellow markings',
        ],
        'impact_label': 'Tough shade flower',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Dietes_grandiflora_kz1.jpg/640px-Dietes_grandiflora_kz1.jpg',
    },

    # ------------------------------------------------------------------
    # PEAT / WETLAND — niche soil coverage
    # ------------------------------------------------------------------
    {
        'name': 'Papyrus',
        'scientific_name': 'Cyperus papyrus',
        'climate_zones': ['tropical_savanna', 'tropical_rainforest'],
        'sun_exposure': ['full_sun', 'partial'],
        'soil_types': ['peat', 'clay'],
        'water_conservation': 'moderate',
        'water_frequency': 'Wet feet always',
        'tags': ['wetland', 'historical', 'fast-growing'],
        'care_tips': [
            'Plant in standing water or saturated soil',
            'Excellent for pond edges',
            'Cut back when stems brown',
        ],
        'impact_label': 'Wetland filter',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Cyperus_papyrus.jpg/640px-Cyperus_papyrus.jpg',
    },
    {
        'name': 'African Bog Lily',
        'scientific_name': 'Crinum macowanii',
        'climate_zones': ['tropical_savanna', 'tropical_highland'],
        'sun_exposure': ['partial', 'full_sun'],
        'soil_types': ['peat', 'loamy', 'clay'],
        'water_conservation': 'moderate',
        'water_frequency': 'Keep moist',
        'tags': ['flowering', 'wetland', 'bulb'],
        'care_tips': [
            'Plant bulbs with neck above soil',
            'Pink-striped trumpet flowers',
            'Don\'t move once established',
        ],
        'impact_label': 'Wetland wildflower',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Crinum_macowanii.jpg/640px-Crinum_macowanii.jpg',
    },

    # ------------------------------------------------------------------
    # CLAY soil specialists
    # ------------------------------------------------------------------
    {
        'name': 'Wild Plum',
        'scientific_name': 'Harpephyllum caffrum',
        'climate_zones': ['tropical_savanna', 'temperate'],
        'sun_exposure': ['full_sun', 'partial'],
        'soil_types': ['clay', 'loamy'],
        'water_conservation': 'low',
        'water_frequency': 'Monthly once established',
        'tags': ['fruit-bearing', 'shade-tree', 'bird-friendly'],
        'care_tips': [
            'Tolerates heavy clay',
            'Edible plum-like fruit',
            'Evergreen canopy',
        ],
        'impact_label': 'Bird-feeder tree',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Harpephyllum_caffrum.jpg/640px-Harpephyllum_caffrum.jpg',
    },
    {
        'name': 'Coral Tree',
        'scientific_name': 'Erythrina caffra',
        'climate_zones': ['tropical_savanna', 'temperate'],
        'sun_exposure': ['full_sun'],
        'soil_types': ['clay', 'loamy'],
        'water_conservation': 'low',
        'water_frequency': 'Monthly',
        'tags': ['flowering', 'wildlife-friendly', 'iconic'],
        'care_tips': [
            'Bright red flowers attract sunbirds',
            'Tolerates clay and seasonal flooding',
            'Plant away from paving — roots lift',
        ],
        'impact_label': 'Sunbird favourite',
        'image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Erythrina_caffra_kz4.jpg/640px-Erythrina_caffra_kz4.jpg',
    },
]


class Command(BaseCommand):
    help = 'Seed the Plant catalogue with sample native African flora.'

    def handle(self, *args, **options):
        created = 0
        for entry in SAMPLE_PLANTS:
            _, was_created = Plant.objects.get_or_create(
                scientific_name=entry['scientific_name'],
                defaults=entry,
            )
            if was_created:
                created += 1

        self.stdout.write(self.style.SUCCESS(
            f'Seeded {created} new plant(s). Total catalogue: {Plant.objects.count()}.'
        ))
