# Generated by Django 5.0.6 on 2026-05-21 13:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('typical_countries', models.JSONField(default=list)),
                ('cooling_strategy', models.CharField(blank=True, max_length=255)),
                ('passive_features', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EcoMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('element_type', models.CharField(choices=[('wall', 'Wall'), ('foundation', 'Foundation'), ('roof', 'Roof'), ('floor', 'Floor'), ('window', 'Window'), ('insulation', 'Insulation')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('sustainability_rationale', models.TextField(blank=True)),
                ('carbon_score', models.FloatField(default=0.0)),
                ('cost_delta_pct', models.FloatField(default=0.0)),
                ('suitable_climate_zones', models.JSONField(default=list)),
                ('is_eco_alternative', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['element_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('bedrooms', models.IntegerField()),
                ('climate_zone', models.CharField(max_length=50)),
                ('style', models.CharField(choices=[('modern', 'Modern'), ('traditional', 'Traditional'), ('hybrid', 'Hybrid')], default='modern', max_length=20)),
                ('orientation', models.CharField(choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West')], default='south', max_length=20)),
                ('layout_json', models.JSONField(default=dict)),
                ('eco_score', models.IntegerField(default=0)),
                ('selected_materials', models.JSONField(default=dict)),
                ('total_area_sqm', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
