# Generated by Django 5.0.6 on 2026-05-02 09:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=150)),
                ('climate_zones', models.JSONField(default=list)),
                ('sun_exposure', models.JSONField(default=list)),
                ('soil_types', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('care_tips', models.JSONField(default=list)),
                ('water_conservation', models.CharField(choices=[('moderate', 'Moderate'), ('low', 'Low'), ('ultra_low', 'Ultra-low')], default='moderate', max_length=20)),
                ('water_frequency', models.CharField(blank=True, max_length=100)),
                ('impact_label', models.CharField(blank=True, max_length=50)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='CareTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('water', 'Water'), ('prune', 'Prune'), ('fertilize', 'Fertilize'), ('repot', 'Repot')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_tasks', to=settings.AUTH_USER_MODEL)),
                ('user_plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_tasks', to='plants.userplant')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
